// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShuKnow.Infrastructure.Persistent;

#nullable disable

namespace ShuKnow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327123028_AddChatSessions")]
    partial class AddChatSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShuKnow.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_sessions");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_sessions_user_id")
                        .HasFilter("\"status\" = 1");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ShuKnow.Infrastructure.Misc.IdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_identity_users");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_identity_users_login");

                    b.ToTable("identity_users", (string)null);
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("ShuKnow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_sessions_users_user_id");
                });

            modelBuilder.Entity("ShuKnow.Infrastructure.Misc.IdentityUser", b =>
                {
                    b.HasOne("ShuKnow.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("ShuKnow.Infrastructure.Misc.IdentityUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_users_users_id");
                });
#pragma warning restore 612, 618
        }
    }
}
