// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShuKnow.Infrastructure.Persistent;

#nullable disable

namespace ShuKnow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShuKnow.Domain.Entities.ChatAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BlobId")
                        .HasColumnType("uuid")
                        .HasColumnName("blob_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_consumed");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_attachments");

                    b.HasIndex("BlobId")
                        .HasDatabaseName("ix_chat_attachments_blob_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_attachments_user_id");

                    b.HasIndex("CreatedAt", "IsConsumed")
                        .HasDatabaseName("ix_chat_attachments_created_at_is_consumed");

                    b.ToTable("chat_attachments", (string)null);
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("SessionId", "Index", "Id")
                        .HasDatabaseName("ix_chat_messages_session_id_index_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_sessions");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_sessions_user_id")
                        .HasFilter("\"status\" = 1");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlobId")
                        .HasColumnType("uuid")
                        .HasColumnName("blob_id");

                    b.Property<string>("ChecksumSha256")
                        .HasColumnType("text")
                        .HasColumnName("checksum_sha256");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("FolderId")
                        .HasDatabaseName("ix_files_folder_id");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Emoji")
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_folder_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_folders");

                    b.HasIndex("ParentFolderId")
                        .HasDatabaseName("ix_folders_parent_folder_id");

                    b.HasIndex("UserId", "ParentFolderId", "Name")
                        .HasDatabaseName("ix_folders_user_id_parent_folder_id_name");

                    b.HasIndex("UserId", "ParentFolderId", "SortOrder")
                        .HasDatabaseName("ix_folders_user_id_parent_folder_id_sort_order");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.UserAiSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ApiKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api_key_encrypted");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<string>("LastTestError")
                        .HasColumnType("text")
                        .HasColumnName("last_test_error");

                    b.Property<int?>("LastTestLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("last_test_latency_ms");

                    b.Property<bool?>("LastTestSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("last_test_success");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_id");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.HasKey("UserId")
                        .HasName("pk_user_ai_settings");

                    b.ToTable("user_ai_settings", (string)null);
                });

            modelBuilder.Entity("ShuKnow.Infrastructure.Misc.IdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_identity_users");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_identity_users_login");

                    b.ToTable("identity_users", (string)null);
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.ChatAttachment", b =>
                {
                    b.HasOne("ShuKnow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_attachments_users_user_id");
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("ShuKnow.Domain.Entities.ChatSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_chat_sessions_session_id");
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("ShuKnow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_sessions_users_user_id");
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.File", b =>
                {
                    b.HasOne("ShuKnow.Domain.Entities.Folder", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_files_folders_folder_id");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.Folder", b =>
                {
                    b.HasOne("ShuKnow.Domain.Entities.Folder", null)
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_folders_folders_parent_folder_id");

                    b.HasOne("ShuKnow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_folders_users_user_id");
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.UserAiSettings", b =>
                {
                    b.HasOne("ShuKnow.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("ShuKnow.Domain.Entities.UserAiSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_ai_settings_users_user_id");
                });

            modelBuilder.Entity("ShuKnow.Infrastructure.Misc.IdentityUser", b =>
                {
                    b.HasOne("ShuKnow.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("ShuKnow.Infrastructure.Misc.IdentityUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_users_users_id");
                });

            modelBuilder.Entity("ShuKnow.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
