namespace ShuKnow.Domain.Enums;

/// <summary>
/// Logical author of a chat message inside a chat session.
/// </summary>
public enum ChatMessageRole
{
    /// <summary>
    /// Message provided by the end user.
    /// </summary>
    User = 0,

    /// <summary>
    /// Message generated by the AI assistant.
    /// </summary>
    Ai = 1
}
