// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PPshu.Infrastructure.Persistent;

#nullable disable

namespace PPshu.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223075057_MakeLoginUnique")]
    partial class MakeLoginUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PPshu.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PPshu.Infrastructure.Misc.IdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_identity_users");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_identity_users_login");

                    b.ToTable("identity_users", (string)null);
                });

            modelBuilder.Entity("PPshu.Infrastructure.Misc.IdentityUser", b =>
                {
                    b.HasOne("PPshu.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("PPshu.Infrastructure.Misc.IdentityUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_users_users_id");
                });
#pragma warning restore 612, 618
        }
    }
}
